# Dependencies
markdown:         redcarpet
highlighter:      pygments
extensions: ["tables"]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            BRAG QUT
tagline:          'One Weird Tip'
description:      'This research group discovered the secret to more efficient data analysis'
url:              http://bragqut.github.io
baseurl:          /

author:
  name:           'Sam Clifford'
  url:            http://samclifford.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bragqut/bragqut.github.io
