# Dependencies
markdown:         kramdown
highlighter:      pygments
extensions: ["tables"]
gems: 
 - jekyll-paginate
 - jekyll-gist

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            One weiRd tip
tagline:          'Cut the time it takes to analyse data'
description:      'This statistics research group discovered the secret to more efficient data processing and analysis. Computer scientists hate them!'
url:              http://bragqut.github.io
baseurl:          /

#author:
#  name:           'Bayesian Research and Applications Group'
#  url:            http://bragqut.wordpress.com

paginate:         5

# Custom vars
version:          2.1.3

github:
  repo:           https://github.com/bragqut/bragqut.github.io
