# Dependencies
markdown:         redcarpet
highlighter:      pygments
extensions: ["tables"]
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            One Weird Tip
tagline:          'One Weird Tip'
description:      'This statistics research group discovered the secret to more efficient data processing an analysis. Computer scientists hate them!'
url:              http://bragqut.github.io
baseurl:          /

author:
  name:           'Sam Clifford'
  url:            http://samclifford.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bragqut/bragqut.github.io
